### ISSUE TITLE
Parsing GPS valid status in RMC bug

### ISSUE THREAD

**Issue by anubisis** [MaJerle/lwgps#19]
Hello,

the Quectel L86 GNSS module is sending RMC in this format:
$GPRMC,190138.000,A,4005.9147,N,01523.0933,E,0.59,268.30,220221,,,A,V*0E
and the library is parsing the status as invalid. It has problem with the decimal point in the UTC time. 
The UTC time is sent in format "hhmmss.sss" (the number 190138.000). If I remove the decimal point part, making the time only "190138", it parses correctly the signal validity status.

**Comment by MaJerle** [comment]
Running this statement, it fails at CRC level. So it would be good to know what is used for CRC in the L86 module.

**Comment by anubisis** [comment]
In the L86 manual, there is only this info about CRC:

> A hexadecimal number calculated by exclusive OR of
all characters between „$‟ and „*‟

**Comment by MaJerle** [comment]
This code:

```c
#include <stdio.h>
#include <string.h>
#include <stdint.h>

const char *gps_stat = ""
//"$"
"GPRMC,190138.000,A,4005.9147,N,01523.0933,E,0.59,268.30,220221,,,A,V"
//"*"
//"0E"
"";

int main() {
    uint8_t crc = 0;
    for (size_t i = 0; i < strlen(gps_stat); ++i) {
        crc ^= gps_stat[i];
    }
    printf("CRC: %02X\r\n", (unsigned)crc);
    return 0;
}
```

Produces:

```
CRC: 12
```

So we are far from value indicated in the end of CRC statement (0x0E)

**Comment by anubisis** [comment]
Sorry, my mistake typing the message. This one is correct:
$GPRMC,123448.000,A,4007.8742,N,01222.9751,E,0.00,96.88,230221,,,A,V*20

GPS is fixed, CRC is OK but the lwgps_t is_valid status is zero == invalid. So I think the problem is not in the CRC, because that works.

**Comment by MaJerle** [comment]
I need more info from your side.

https://repl.it/talk/share/LwGPS-test-with-GPRMC-from-Quectel/123887

It works well with your use case.

**Comment by anubisis** [comment]
Well, I am runnig it on STM32L471 MCU (System Workbench form STM32 IDE), collecting bytes from L86. When there is full package from the L86 (starting with RMC message and ending with TXT message - special case for L86) the data package is then processed with `lwgps_process(&gps, gnss_rx_buffer, gnss_rx_data_size);`
This is the whole data package which is fed into lwgps_process:

> $GPRMC,123448.000,A,4007.8742,N,01422.9751,E,0.00,96.88,230221,,,A,V*26
$GPVTG,96.88,T,,M,0.00,N,0.00,K,A*02
$GPGGA,123448.000,4007.8742,N,01422.9751,E,1,6,4.85,266.8,M,45.5,M,,*50
$GNGSA,A,3,15,19,17,24,,,,,,,,,4.92,4.85,0.85,1*06
$GNGSA,A,3,73,82,,,,,,,,,,,4.92,4.85,0.85,2*07
$GPGSV,3,1,10,12,73,263,16,24,70,141,20,19,41,058,19,25,28,256,,0*62
$GPGSV,3,2,10,32,27,311,,17,22,043,29,06,19,094,15,15,15,188,19,0*66
$GPGSV,3,3,10,02,11,130,,10,04,272,,0*66
$GLGSV,3,1,09,73,66,051,21,74,47,300,,83,46,096,,72,35,275,,1*76
$GLGSV,3,2,09,82,30,035,17,65,24,325,,80,20,089,17,71,16,224,,1*70
$GLGSV,3,3,09,84,15,157,,1*4A
$GNGLL,4007.8742,N,01422.9751,E,123448.000,A,A*4A
$GPTXT,01,01,02,ANTSTATUS=OPEN*2B

The length in bytes is about 700 B. Again, if I feed this directly to the lwgps_process via const array, the valid indicator is wrong. But if I delete the point and zeroes on the UTC time (123448.000 -> 123448), the valid indicator is correct.

**Comment by MaJerle** [comment]
Taking your data on the input, adding CRLF characters at the end (as they should be), I see perfect result.
Can you post your LWGPS configuration settings (in case you don't use default one)?

![image](https://user-images.githubusercontent.com/405717/108910948-e2bffd80-7626-11eb-89a7-a10a5d93bda4.png)

**Comment by anubisis** [comment]
I am using the default config file (lwgps_opt.h) without any modification.
Ok, this is strange. New behaviour: If I put the gps_rx_data as const in the program (as you did), it works. But if I feed the buffer from GPS module, it has problem with the validity of the data and also with satellite numbers. About satellite numbers - I noticed  it today when I was testing the device in the field. After some time I get number of satellites in the view smaller than number of satellites which are used (view: 14, used: 16).
But the longitude and lattitude are always correct. If I send the whole gps_rx_data buffer to the debug UART port, it looks OK.
So the lwgps_process is receiving correct data, or at least there are no wrong characters etc. on the debug UART.

Also I noticed small bug in the function for calculating the distance and bearings between two coordinates (it returns distance in [km] and not in [m] as it should according documentation).

In today's testing in the field I noticed more bugs, for example the speed is calculated wrong, the COG also (COG after few updates just hangs on some bearing, it is similar to the bug with satellites number - it also hangs on some number after while of using).

I am kind of confused with this behaviour. For debug purposes - I will log over UART the gps_rx_data buffer which is fed into the lwgps for some time, maybe there will be something wrong. But I doubt it.
I'll be back with the log later.

**Comment by MaJerle** [comment]
Anubisis,

if you find erratic data parsed with the lib, let me know the actual (erratic) calculated output vs the (correct) input.

**Comment by anubisis** [comment]
Ok.

About the distance, I am feeding the function with this code:
`float temp_dis, temp_bear;
lwgps_distance_bearing(prev_la_avg, prev_lo_avg, la, lo, &temp_dis, &temp_bear);`
where all of the variables are float type.
If I feed it with constant lattitude and longitude as this:
`lwgps_distance_bearing(50.107438, 14.449760, 50.101912, 14.450012, &temp_dis, &temp_bear);`
The value in temp_dis is 3.598. The actual distance between these two points is 618 m.

Edit: I see the problem. Library is using the double, I was using float. I didn't think this could make such big problems. Now the distance is correctly calculated.

**Comment by MaJerle** [comment]
> Edit: I see the problem. Library is using the double, I was using float. I didn't think this could make such big problems. Now the distance is correctly calculated.

You can setup configuration to use either float or doubles for these calculations.

> yes, the CRC calc is wrong as I was mentioning this in the first post. If I remove the decimal part from the time (the 000 zeroes), it works:
> ![image](https://user-images.githubusercontent.com/15860554/109390800-f2379300-7913-11eb-96b4-6f1eaaca4e84.png)

Are you then saying that lib in fact works perfectly OK just there is an issue with CRC data from the modem?

**Comment by anubisis** [comment]
Yes, when there is valid data from the GPS module, it calculates wrong the CRC. But only for RMC packet, other packets have good CRC. I will write the Quectel manufacturer if he can fix it.
Sorry for the confusion, I didn't expect such problems with the hardware.

Btw, meantime, is it possible to add some define (if statement) for ignoring the CRC in your library? Small workaround for this issue...

**Comment by MaJerle** [comment]
Added on `develop` branch

**Comment by anubisis** [comment]
Thanks!

**Comment by Mohamedayouni** [comment]
Can you please share your code because I work with Quectel l86-M33 and I didn't find a code works .
