### ISSUE TITLE
How to extend to more sentences?

### ISSUE THREAD

**Issue by abhinandanudupa** [MaJerle/lwgps#22]
Hello!
I want to know you have a guide or any suggestions for extending the parsing to sentences like `$GPGLL`, `$GPZDA`. I plan on extending parsing to sentences like `$GPZDA` soon and want to seen if you had any ideas that could help.

More importantly, would it be a good idea to use the library in mission critical systems were speed, memory footprint and accuracy would be immensely important? I understand that 'speed, memory footprint and accuracy' is a bit vague but I do not have the exact specifications as of now. But can you give an example where it was used in a mission critical system like in a satellite?

**Comment by MaJerle** [comment]
> I want to know you have a guide or any suggestions for extending the parsing to sentences like `$GPGLL`, `$GPZDA`. I plan on extending parsing to sentences like `$GPZDA` soon and want to seen if you had any ideas that could help.

This library meant to be super lightweight and provide essential requiremets for key NMEA statements to determine position, speed, altitude, date, time and satellites.

I developed, prior this one, also STm32-based GPS, that had *custom field* functionality, but it required malloc at that time, to have internal list management and to update new value to user only when there was really a new value.

https://github.com/MaJerle/stm32fxxx-hal-libraries/blob/1feae687f99552832ff82ede6558d5266eec6201/00-STM32_LIBRARIES/tm_stm32_gps.c#L215-L237

I did not plan something like that here, but it doesn't mean we could not add it.

> More importantly, would it be a good idea to use the library in mission critical systems were speed, memory footprint and accuracy would be immensely important? I understand that 'speed, memory footprint and accuracy' is a bit vague but I do not have the exact specifications as of now. But can you give an example where it was used in a mission critical system like in a satellite?

All 3 things together are certainly a challenge:

- Speed: Processing only of essential things, char parsing sometimes with char-by-char conversion from string to int
- Memory footprint: Why is it important for *mission critical*? (I have no background here, hence my couriosity). Footprint can be adjusted to only parse necessary things
- Accuracy: Uses float or double point for precision, user defined (*double* preferred for high accuracy for sure)
- Reliability: it uses CRC to validate string before it confirms data are OK

**Comment by abhinandanudupa** [comment]
> I developed, prior this one, also STm32-based GPS, that had _custom field_ functionality, but it required malloc at that time, to have internal list management and to update new value to user only when there was really a new value.
> 
> https://github.com/MaJerle/stm32fxxx-hal-libraries/blob/1feae687f99552832ff82ede6558d5266eec6201/00-STM32_LIBRARIES/tm_stm32_gps.c#L215-L237

Thank you for this resource, will look into it.

> * Memory footprint: Why is it important for _mission critical_? (I have no background here, hence my couriosity). Footprint can be adjusted to only parse necessary things

I believe that right now we are looking at a system using only 512 MB of RAM.

**Comment by abhinandanudupa** [comment]
> I did not plan something like that here, but it doesn't mean we could not add it.

How would you go about doing that? Where to start from?

**Comment by MaJerle** [comment]
> I believe that right now we are looking at a system using only 512 MB of RAM.

This library takes max 3kB flash and far less than 1kB RAM, seems to be on a safe side.

> How would you go about doing that? Where to start from?

I suppose a new processing function should handle "custom" entries next to the all others.

**Comment by abhinandanudupa** [comment]
Thank you!
